### ISSUE TITLE
Adding mobile menu

### ISSUE THREAD

**Issue by M0rrighan** [elmar8287/elmar8287.github.io#2]
Hi @elmar8287, you really did a great job with your clean and organized cod. You implemented simple functions, looks great!

**Comment by Tchilo** [comment]
Elmar you have done amazing work here.

**Comment by elmar8287** [comment]
> Hi @elmar8287, you really did a great job with your clean and organized cod. You implemented simple functions, looks great!

@M0rrighan @Tchilo Thanks guys!
